### PR TITLE
Add config file support with tests

### LINKED ISSUE #1: Config file for CLI
A config file is something quality tools have. It would allow developers to have per-directory access tokens among other things. .ini style is (see Python's distutils or https://pip.pypa.io/en/latest/user_guide.html#config-file) one way to go.

Replaces https://github.com/mapbox/mapbox-sdk-py/issues/25.

### LINKED ISSUE #30: Add a mapbox-config command
Sort of like npm-config. It would tell the user

- active access token 
- output verbosity

and whether these values are coming from environment variables or config file. It's also going to be handy for configuration testing.

### PR DESCRIPTION
**Pull request by sgillies**
Closes #1
Closes #30

### CODE REVIEW

**Comment by sgillies** [comment]
Ready for :eyes: @perrygeo.

There's not much config file support for anything other than access tokens, but there's a pattern we could spread to other commands. We could even allow users to specify different tokens per command using config blocks.

```ini
[mapbox]
access-token = pk.lolwut

[upload]
access-token = pk.foobar
```

**Comment by perrygeo** [comment]
This part of the `mapbox config` output is a little confusing
```
Config file /Users/mperry/Library/Application Support/mapbox/mapbox.ini:
```
My first thought was to check that config file ("did it get created on install?") but it didn't yet exist.

Maybe we should explicitly say:
```
Config file /Users/mperry/Library/Application Support/mapbox/mapbox.ini: NOT PRESENT
```
and maybe even add something like an example config that could be copy and pasted? Or even a `config --write` option to write the current context out to the config file?

**Comment by perrygeo** [comment]
With the exception of my confusion above and the needs for a doc/example, this looks good to go. :+1:

**Comment by sgillies** [comment]
@perrygeo great suggestions. here's the help now:

```
$ mapbox --help
Usage: mapbox [OPTIONS] COMMAND [ARGS]...

  This is the command line interface to Mapbox web services.

  Mapbox web services require an access token. Your token is shown on the
  https://www.mapbox.com/developers/api/ page when you are logged in. The
  token can be provided on the command line

    $ mapbox --access-token MY_TOKEN ...

  as an environment variable named MAPBOX_ACCESS_TOKEN or MapboxAccessToken

    $ export MAPBOX_ACCESS_TOKEN=MY_TOKEN
    $ mapbox ...

  or in a config file

    ; configuration file mapbox.ini
    [mapbox]
    access-token = MY_TOKEN

  The OS-dependent default config file path is something like

    ~/Library/Application Support/mapbox/mapbox.ini
    ~/.config/mapbox/mapbox.ini
    ~/.mapbox/mapbox.ini

Options:
  --version            Show the version and exit.
  -v, --verbose        Increase verbosity.
  -q, --quiet          Decrease verbosity.
  --access-token TEXT  Your Mapbox access token.
  -c, --config PATH    Config file
  --help               Show this message and exit.
```

**Pull request merged**
