### PR TITLE
upload arguments

### LINKED ISSUE #67: No read method on valid file upload
Just got this somewhat-cryptic message on trying to upload [this valid demo geojson file](https://gist.github.com/wboykinm/63bc9c44d6672a0aeda2)
```
| => mapbox upload --name landplanner.demopoints demo.geojson
Usage: mapbox upload [OPTIONS] TILESET [INFILE]

Error: Invalid value: Object `None` has no .read method, a file-like object is required
```

My key is properly configured (I gave it all 12 scopes just in case) and exported to `$MAPBOX_ACCESS_TOKEN`, and the file is valid, so I'm not sure what's going on here. Is my account missing some authorization globally?

### PR DESCRIPTION
**Pull request by perrygeo**
Resolves #67 

@sgillies I can't remember why [we made INFILE an optional argument here](https://github.com/mapbox/mapbox-cli-py/commit/4040fa2423f5e71e3c446ec32e547d8ab11cf413#diff-34b9229ac645b1463fbde07616927c2aR9). Seems like it should be required, right?

### CODE REVIEW

**Comment by perrygeo** [comment]
related, maybe it's time to rethink the upload args?  See #50

**Comment by perrygeo** [comment]
Per voice with@sgillies and considering #50, we're going to take a different approach

1.  Make arguments `TILESET SOURCE DESTINATION` for file sources, `TILESET DESTINATION` for stdin.
2. Make `--name` default to the basename of the file, If the file is stdin, default to the TILESET minus username.
3. If reading from stdin, notify user via stderr that it's waiting on an input stream.

**Comment by perrygeo** [comment]
@sgillies How does this feel? The new usage looks like:

```
Usage: mapbox upload [OPTIONS] [INFILE] TILESET

  Upload data to Mapbox accounts. All endpoints require authentication.
  Uploaded data lands at https://www.mapbox.com/data/ and can be used in new
  or existing projects.

  You can specify the input file and tileset id

    $ mapbox upload mydata.geojson username.data

  Or specify just the tileset id and take an input file on stdin

    $ cat mydata.geojson | mapbox upload username.data

  The --name option defines the title as it appears in Studio and defaults
  to the last part of the tileset id, e.g. "data"

  Note that the tileset must start with your username. An access token with
  upload scope is required, see `mapbox --help`.

Options:
  --name TEXT  Name for the data upload
  --help       Show this message and exit.
```

In terms of backwards compatibility, the new arg order means you'll see this message if you try to use the old order:
```
Error: Invalid value: Could not open file: <username>.<tilesetid>
```
Is that sufficient or should we warn louder that the order has changed?

**Comment by sgillies** [comment]
@perrygeo How about something like 

`Error: Invalid value: Could not open file: <username>.<tilesetid> (check order of command arguments!)`

**Comment by perrygeo** [comment]
Hm, something's still awry with the stdin stream

```
$ cat data.geojson | mapbox upload perrygeo.data
Reading data from stdin (Hit Ctl-C to cancel) ...
Usage: mapbox upload [OPTIONS] [INFILE] TILESET

Error: Invalid value: [Errno 29] Illegal seek
```

The same command specifying the file path works.

**Comment by perrygeo** [comment]
Looking deeper into this exception, I see, 

```
  File "/Users/mperry/work/mapbox-sdk-py/mapbox/services/uploads.py", line 65, in stage
    res = s3.Object(creds['bucket'], creds['key']).put(Body=fileobj)
...
  File "/Users/mperry/env/mapbox/lib/python2.7/site-packages/botocore/handlers.py", line 140, in _calculate_md5_from_file
    start_position = fileobj.tell()
IOError: [Errno 29] Illegal seek
```

So it looks like boto needs to precompute an md5 hash before uploading, at least with the `s3` object interface. Since you can't seek on a stream, there's no way to do that.

I'll continue digging but I see lots of questions, no solid solutions. My guess is that, if it is possible to stream stdin to s3 objects, it will require rewriting the s3 handling code in the SDK to use the lower level `s3_client` interface.

SO where does that leave this PR? I'd say go back to requiring INFILE and open a new ticket for stream upload handling in the SDK. @sgillies?

**Comment by sgillies** [comment]
@perrygeo Interesting. I wasn't thinking of streaming to S3 so much as wanting mapbox-upload to be able to accept the output of, say, fio-cat. We'd have to accumulate the input features within mapbox-upload, certainly, and I think it would be worth doing.

But if we need to push that to a future release in order to get the next one out, I'm fine with that.

**Comment by perrygeo** [comment]
Ah, stream *in*, but not *out*. Makes sense to me. I think that would be worth doing before merging this PR.

**Comment by perrygeo** [comment]
Tricky part about supporting `fio cat` and feature sequences is that their contents are not, by themselves, valid JSON. I'd say for now just stick `fio collect` in the pipe and assume the input to `mapbox upload` is a valid file.

**Comment by perrygeo** [comment]
The other challenge with accumulating the input file contents in general, GeoJSON feature sequences not withstanding, is that the `upload` function in the SDK takes an open file handle, not the file contents. We'd need to pull the contents into a memory file with [BytesIO](https://docs.python.org/2/library/io.html#io.BytesIO). Worth pursuing this?

**Comment by perrygeo** [comment]
@sgillies this is ready to go but might require coordinating some documentation changes. Thoughts?

**Comment by sgillies** [comment]
@perrygeo are you asking if we can merge this before we update docs on mapbox.com? I think we can if we like, as long as we have up to date docs in this repo. However, let's make sure we have mapbox.com docs ready to go before we make a new release and publish to pypi.

**Pull request merged**
